[2025-09-17T01:15:44.349+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_test_production_summary.create_test_production_summary scheduled__2025-09-16T00:00:00+00:00 [queued]>
[2025-09-17T01:15:44.355+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_test_production_summary.create_test_production_summary scheduled__2025-09-16T00:00:00+00:00 [queued]>
[2025-09-17T01:15:44.356+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-17T01:15:44.368+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_test_production_summary> on 2025-09-16 00:00:00+00:00
[2025-09-17T01:15:44.373+0000] {standard_task_runner.py:60} INFO - Started process 68 to run task
[2025-09-17T01:15:44.376+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_test_production_summary', 'create_test_production_summary', 'scheduled__2025-09-16T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/sql_flow.py', '--cfg-path', '/tmp/tmpuhobemps']
[2025-09-17T01:15:44.379+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask create_test_production_summary
[2025-09-17T01:15:44.429+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_test_production_summary.create_test_production_summary scheduled__2025-09-16T00:00:00+00:00 [running]> on host c6016013c48b
[2025-09-17T01:15:44.488+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_test_production_summary' AIRFLOW_CTX_TASK_ID='create_test_production_summary' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-16T00:00:00+00:00'
[2025-09-17T01:15:44.571+0000] {logging_mixin.py:188} INFO - Error: column dt.Route_Card_Journal does not exist
LINE 11:             ON pj."Route_Card_Journal" = dt."Route_Card_Jour...
                                                  ^
HINT:  Perhaps you meant to reference the column "dt.Route_Card_Jounal".
[2025-09-17T01:15:44.572+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sql_flow.py", line 38, in create_test_production_summary
    cursor.execute(create_view_query)
psycopg2.errors.UndefinedColumn: column dt.Route_Card_Journal does not exist
LINE 11:             ON pj."Route_Card_Journal" = dt."Route_Card_Jour...
                                                  ^
HINT:  Perhaps you meant to reference the column "dt.Route_Card_Jounal".

[2025-09-17T01:15:44.583+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag1_test_production_summary, task_id=create_test_production_summary, execution_date=20250916T000000, start_date=20250917T011544, end_date=20250917T011544
[2025-09-17T01:15:44.594+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task create_test_production_summary (column dt.Route_Card_Journal does not exist
LINE 11:             ON pj."Route_Card_Journal" = dt."Route_Card_Jour...
                                                  ^
HINT:  Perhaps you meant to reference the column "dt.Route_Card_Jounal".
; 68)
[2025-09-17T01:15:44.629+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-17T01:15:44.643+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-17T10:24:57.239+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_test_production_summary.create_test_production_summary scheduled__2025-09-16T00:00:00+00:00 [queued]>
[2025-09-17T10:24:57.243+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_test_production_summary.create_test_production_summary scheduled__2025-09-16T00:00:00+00:00 [queued]>
[2025-09-17T10:24:57.244+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-17T10:24:57.252+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_test_production_summary> on 2025-09-16 00:00:00+00:00
[2025-09-17T10:24:57.257+0000] {standard_task_runner.py:60} INFO - Started process 79 to run task
[2025-09-17T10:24:57.259+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_test_production_summary', 'create_test_production_summary', 'scheduled__2025-09-16T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/sql_flow.py', '--cfg-path', '/tmp/tmp91wha2uz']
[2025-09-17T10:24:57.267+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask create_test_production_summary
[2025-09-17T10:24:57.347+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_test_production_summary.create_test_production_summary scheduled__2025-09-16T00:00:00+00:00 [running]> on host 08f82a781ed8
[2025-09-17T10:24:57.428+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_test_production_summary' AIRFLOW_CTX_TASK_ID='create_test_production_summary' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-16T00:00:00+00:00'
[2025-09-17T10:24:57.539+0000] {logging_mixin.py:188} INFO - Error: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(test_production_summary, 2200) already exists.
[2025-09-17T10:24:57.540+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sql_flow.py", line 38, in create_test_production_summary
    cursor.execute(create_view_query)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(test_production_summary, 2200) already exists.

[2025-09-17T10:24:57.551+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag1_test_production_summary, task_id=create_test_production_summary, execution_date=20250916T000000, start_date=20250917T102457, end_date=20250917T102457
[2025-09-17T10:24:57.559+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task create_test_production_summary (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(test_production_summary, 2200) already exists.
; 79)
[2025-09-17T10:24:57.592+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-17T10:24:57.603+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-17T10:34:33.438+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_test_production_summary.create_test_production_summary scheduled__2025-09-16T00:00:00+00:00 [queued]>
[2025-09-17T10:34:33.443+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_test_production_summary.create_test_production_summary scheduled__2025-09-16T00:00:00+00:00 [queued]>
[2025-09-17T10:34:33.444+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-17T10:34:33.451+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_test_production_summary> on 2025-09-16 00:00:00+00:00
[2025-09-17T10:34:33.456+0000] {standard_task_runner.py:60} INFO - Started process 79 to run task
[2025-09-17T10:34:33.460+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_test_production_summary', 'create_test_production_summary', 'scheduled__2025-09-16T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/sql_flow.py', '--cfg-path', '/tmp/tmpb31xlmgr']
[2025-09-17T10:34:33.463+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask create_test_production_summary
[2025-09-17T10:34:33.541+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_test_production_summary.create_test_production_summary scheduled__2025-09-16T00:00:00+00:00 [running]> on host e8ada05d9c66
[2025-09-17T10:34:33.640+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_test_production_summary' AIRFLOW_CTX_TASK_ID='create_test_production_summary' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-16T00:00:00+00:00'
[2025-09-17T10:34:33.728+0000] {logging_mixin.py:188} INFO - View Test_Production_summary ถูกสร้างแล้ว
[2025-09-17T10:34:33.729+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-17T10:34:33.736+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag1_test_production_summary, task_id=create_test_production_summary, execution_date=20250916T000000, start_date=20250917T103433, end_date=20250917T103433
[2025-09-17T10:34:33.753+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-17T10:34:33.763+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
